@startmindmap

skinparam backgroundColor #FFFFFF
skinparam shadowing false
skinparam defaultFontSize 11
skinparam mindmapDiagram {
  node {
    BackgroundColor lightGray
  }
  rootNode {
    BackgroundColor white
  }
}

title PBS General - TFG WodBuster AI\nPlataforma de Análisis de Ejercicios con IA

* Aplicación web para gestión\nde entrenamientos con IA
** Planificación
** Análisis
** Diseño
** Desarrollo
** Pruebas
** Despliegue
** Documentación
** Reuniones

@endmindmap
